INSERT INTO public.workplace (id, name) VALUES (1, 'Google
');
INSERT INTO public.workplace (id, name) VALUES (2, 'Szegedi Tudományegyetem');
INSERT INTO public.workplace (id, name) VALUES (3, 'MOL');
INSERT INTO public.workplace (id, name) VALUES (4, 'Amazon');
INSERT INTO public.workplace (id, name) VALUES (5, 'Budapesti Közlekedési Társaság');
INSERT INTO public.workplace (id, name) VALUES (6, 'Foxconn');
INSERT INTO public.workplace (id, name) VALUES (8, 'Lind PLC');
INSERT INTO public.workplace (id, name) VALUES (9, 'Renner-Shanahan');
INSERT INTO public.workplace (id, name) VALUES (10, 'Strosin-Schinner');
INSERT INTO public.workplace (id, name) VALUES (11, 'Borer LLC');
INSERT INTO public.workplace (id, name) VALUES (12, 'Flatley, Legros and Hoeger');
INSERT INTO public.workplace (id, name) VALUES (13, 'Marks, Reilly and Lakin');
INSERT INTO public.workplace (id, name) VALUES (14, 'Funk, Daniel and Blanda');
INSERT INTO public.workplace (id, name) VALUES (15, 'Hintz-Cummerata');
INSERT INTO public.workplace (id, name) VALUES (16, 'Hilll, Fahey and Paucek');
INSERT INTO public.workplace (id, name) VALUES (17, 'Stehr, Sporer and Berge');
INSERT INTO public.workplace (id, name) VALUES (18, 'Hermiston PLC');
INSERT INTO public.workplace (id, name) VALUES (19, 'Johnston, Trantow and Reichert');
INSERT INTO public.workplace (id, name) VALUES (20, 'Raynor, Cormier and Frami');
INSERT INTO public.workplace (id, name) VALUES (21, 'Jakubowski PLC');
INSERT INTO public.workplace (id, name) VALUES (22, 'Rutherford-Kerluke');
INSERT INTO public.workplace (id, name) VALUES (23, 'Walter-Shields');
INSERT INTO public.workplace (id, name) VALUES (24, 'Haag-Tromp');
INSERT INTO public.workplace (id, name) VALUES (25, 'Little, Luettgen and Cummerata');
INSERT INTO public.workplace (id, name) VALUES (26, 'Cormier, Dibbert and Lueilwitz');
INSERT INTO public.workplace (id, name) VALUES (27, 'Rau LLC');
INSERT INTO public.workplace (id, name) VALUES (28, 'Gerhold-Carter');
INSERT INTO public.workplace (id, name) VALUES (29, 'Lang LLC');
INSERT INTO public.workplace (id, name) VALUES (30, 'Kihn-Rice');
INSERT INTO public.workplace (id, name) VALUES (31, 'Dare-Rice');
INSERT INTO public.workplace (id, name) VALUES (32, 'Schamberger-Welch');