INSERT INTO public.school (id, name) VALUES (3, 'Budapesti Corvinus Egyetem');
INSERT INTO public.school (id, name) VALUES (1, 'University of Szeged');
INSERT INTO public.school (id, name) VALUES (2, 'University of California');
INSERT INTO public.school (id, name) VALUES (4, 'University of Groningen');
INSERT INTO public.school (id, name) VALUES (5, 'University of Oxford');
INSERT INTO public.school (id, name) VALUES (6, 'Columbia University');
INSERT INTO public.school (id, name) VALUES (7, 'Harward University');
INSERT INTO public.school (id, name) VALUES (8, 'Stanford University');
INSERT INTO public.school (id, name) VALUES (9, 'Princeton University');
INSERT INTO public.school (id, name) VALUES (10, 'Cambridge University');
INSERT INTO public.school (id, name) VALUES (11, 'University of Marocco');
INSERT INTO public.school (id, name) VALUES (12, 'University of Michigan');
INSERT INTO public.school (id, name) VALUES (13, 'Cornell University');
INSERT INTO public.school (id, name) VALUES (14, 'Imperial College London');
INSERT INTO public.school (id, name) VALUES (15, 'University of Alacá');